In [89]:
import numpy as np

In [90]:
# ### Basics

a = np.array([1,2,3], dtype = 'int16')
print(a)


[1 2 3]


In [91]:
#2-D Array
b = np.array([[5.0,6.0,7.0], [3.0,2.0,8.0]])
print(b)

[[5. 6. 7.]
 [3. 2. 8.]]


In [92]:
#Get Dimension
a.ndim
b.ndim

2

In [93]:
#Shape(Rows and Columns)
a.shape
b.shape

(2, 3)

In [94]:
#Get Type
a.dtype

dtype('int16')

In [95]:
#Get Size
a.itemsize

2

In [96]:
#Get Total Size
a.nbytes

6

In [97]:
#2D Array
c = np.array([[1,2,3,4,5,6,7], [10,11,12,13,14,17,16]])
print(c)

#Getting a specific element [r,c]
c[1,5]

[[ 1  2  3  4  5  6  7]
 [10 11 12 13 14 17 16]]


17

In [98]:
#Getting a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [99]:
#Getting a specific column
c[:, 3]

array([ 4, 13])

In [100]:
#Changing element
c[0, 2] = 4
print(c)


[[ 1  2  4  4  5  6  7]
 [10 11 12 13 14 17 16]]


In [101]:
#Changing element of column
c[:, 2] = [1,2]
print(c)

[[ 1  2  1  4  5  6  7]
 [10 11  2 13 14 17 16]]


In [102]:
#3D Array
d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [103]:
#All Zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [104]:
#All 1's matrix (Dimension, Rows, Columns)
np.ones((4,2,2), dtype = 'int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [105]:
#Any other number
np.full((2,2), 99)


array([[99, 99],
       [99, 99]])

In [106]:
#Like any other array
np.full_like(a, 4)


array([4, 4, 4], dtype=int16)

In [107]:
#Random decimal numbers
np.random.rand(4,2)


array([[0.11665957, 0.00191046],
       [0.05099118, 0.28518419],
       [0.54203288, 0.14734169],
       [0.69514576, 0.27104327]])

In [108]:
#Random Integer Value
np.random.randint(4,7, size=(3,3))

array([[6, 5, 6],
       [5, 6, 6],
       [6, 5, 6]])

In [109]:
#Identity Matrix
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
#Repeat an Array
arr = [[1,2,3]]
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [111]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [112]:
#Copying Arrays
e = np.array([1,2,3])
f = e.copy()
print(e)
f[1] = 100
print(f)

[1 2 3]
[  1 100   3]


In [113]:
# ### Mathematics
e + 2

array([3, 4, 5])

In [114]:
e - 2

array([-1,  0,  1])

In [115]:
e / 2

array([0.5, 1. , 1.5])

In [116]:
e + f

array([  2, 102,   6])

In [117]:
e ** 2

array([1, 4, 9], dtype=int32)

In [118]:
#Take the Sin
np.sin(e)

array([0.84147098, 0.90929743, 0.14112001])

In [119]:
# ### Linear Algebra


#Multiplying Matrixes
g = np.ones((2,3))
print(g)
h = np.full((3,2), 2)
print(h)

np.matmul(g,h)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [120]:
#Determinant of a Matrix
i = np.identity(3)
np.linalg.det(i)


1.0

In [121]:
### Statistics

stats = np.array([[1,2,3], [4,5,6]])
print(stats)


[[1 2 3]
 [4 5 6]]


In [122]:
np.min(stats)

1

In [123]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [124]:
# ### Reorganizing Arrays


before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [125]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [126]:
#Vertically Stacking Matrix
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [127]:
#Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])